import { AfterViewInit, Component, EventEmitter, Input, Output, ViewChild } from '@angular/core';
import AOS from 'aos'

declare var $: any;
import 'aos/dist/aos.css';

import { WelcomeService } from '../admin-dashboard/welcome/welcome.service';
import { AiComponent } from './ai/ai.component';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements AfterViewInit {
@Input()  isAiVisible:boolean = false
@Output() isVisibleChange:EventEmitter<boolean>=new EventEmitter<boolean>()
 
  typedText = '';
  fullText = 'You can see that I am an ideal candidate for your job. My AI tool provides a comprehensive overview of my skills and what I can bring to your project, including areas that are new to me.';
  textIndex = 0;



  title = 'angular';
 
  isActive = true;
  private sections: HTMLElement[] = [];
  private currentSectionIndex = 0;
  ngAfterViewInit(): void {
    
    $.scrollify({
      section: ".page",
      sectionName: "section-name",
      interstitialSection: "",
      easing: "easeInOutQuart",
      scrollSpeed: 2000,
      offset: 10,
      scrollbars: true,
      standardScrollElements: "",
      setHeights: true,
      overflowScroll: true,
      updateHash: false,
      touchScroll: true,
      before: function () { },
      after: function () { },
      afterResize: function () { },
      afterRender: function () { }
    })

    AOS.init();



  }
  onDataReceived(data: boolean) {
    this.isActive = data; // Update the variable with data from child
  }
  btnvisible :boolean= false;
  typeText() {
    const typingSpeed = 10; // Speed in ms
    const interval = setInterval(() => {
      if (this.textIndex < this.fullText.length) {
        this.typedText += this.fullText[this.textIndex];
        this.textIndex++;
      } else {
        this.btnvisible=true;
        clearInterval(interval); // Stop when the full text is typed
      }
    }, typingSpeed);
  }


 
openPopup(){
  this.isAiVisible=true;
 
}
flystat = false;
ishover = false;
onMouseEnter(){
  this.ishover=true
}
onMouseOut(){
  this.ishover=false
}
intervalId = setInterval(() => {
  this.flystat = true; // Set flystat to true
  console.log('flystat is set to true');

  // After 1 second, set flystat back to false
  setTimeout(() => {
    this.flystat = false;
    console.log('flystat is set back to false');
  }, 5000); // 1 second delay
}, 20000); 

/* 

allKeywords=[
  "RESTful APIs",
  "message queues",
  "Docker",
  "GCP Pub/Sub",
  "Google Cloud Run",
  "SaaS",
  "IaaS",
  "Decentralized Applications (DApps)",
  "Tokenization",
  "AI Models",
  "NoSQL Databases",
  "MongoDB",
  "Redis",
  "SQL Databases",
  "MySQL",
  "SQLite",
  "MongoDB Atlas",
  "Reactive Programming",
  "Imperative Programming",
  "TDD (Test-Driven Development)",
  "Agile Development",
  "Kanban",
  "DevOps",
  "Software Development Life Cycle (SDLC)",
  "Continuous Delivery",
  "Identity Access Management",
  "JWT (JSON Web Tokens)",
  "PKI (Public Key Infrastructure)",
  "SQL Injection",
  "Firewalls",
  "IAM (Identity and Access Management)",
  "Cloud Firewalls",
  "GDPR",
  "Continuous Monitoring",
  "App Monitoring",
  "ISO 9001",
  "Low-Code Development",
  "Headless CMS",
  "Web App Frameworks",
  "Backend Development",
  "UX/UI Design",
  "Prototyping",
  "UI Prototyping",
  "Adobe XD",
  "Usability Testing",
  "User Research",
  "CSS3",
  "JavaScript",
  "React",
  "Angular",
  "Tailwind CSS",
  "Sass",
  "Node.js",
  "Next.js",
  "Server-Side Rendering (SSR)",
  "API Integration",
  "REST APIs",
  "WebSockets",
  "PWA (Progressive Web App)",
  "CI/CD Tools",
  "GitLab",
  "Bitbucket",
  "Chef",
  "JUnit",
  "TestNG",
  "Postman",
  "Usability Testing",
  "Mobile Testing",
  "Content Delivery Networks (CDN)",
  "Redis",
  "API Gateway",
  "Proxy Servers",
  "Nginx",
  "NGINX Plus",
  "Cloud App Development",
  "Android Development",
  "React Native",

  "Android SDK",
  "Cross-Platform Mobile Development",
  "Play Store",
  "Mobile UI/UX",
  "Google Firebase",
  "Google Analytics",
  "Mobile CI/CD",
  "Device Testing",
  "Service Virtualization",
  "Behavior-Driven Development",
  "Usability Engineering",
  "Embedded Systems",
  "Agile methodologies",
  "Kanban",
  "Extreme Programming (XP)",
  "Continuous Integration (CI)",
  "Software Development Life Cycle (SDLC)",
  "Sprint planning",
  "Sprint Backlog",
  "Product Owner",
  "Burndown charts",
  "Velocity tracking",
  "Retrospective",
  "Cross-functional teams",
  "Project scope management",
  "Project estimation",
  "Task management tools",
  "Trello",
  "Basecamp",
  "Git",
  "GitLab",
  "Version control",
  "Forking workflows",
  "Pull requests",
  "Code collaboration",
  "Gitflow",
  "CI/CD pipelines",
  "Configuration management",
  "Chef",
  "Jenkins",
  "Testing frameworks",
  "JUnit",
  "Behavior-Driven Development (BDD)",
  "Branch management",
  "Release management",
  "Change control process",
  "Team collaboration",
  "Virtual collaboration tools",
  "Slack",
  "Zoom",
  "Webex",
  "Miro",
  "Documentation management",
  "Workflow automation",
  "SOP (Standard Operating Procedure)",
  "Time management",
  "Risk mitigation strategies",
  "Team motivation",
  "Conflict resolution",
  "Cross-functional collaboration",
  "Project reporting",
  "Client requirements gathering",
  "Project documentation",
  "User stories",
  "Agile coaching",
  "Daily stand-ups",
  "Agile maturity assessments",
  "Process improvement",
  "Documentation versioning",
  "Task prioritization",
  "Agile transformations",
  "Quality control",
  "Project dependencies",
  "Project Health Dashboards",
  "Customer success management",
  "Remote work culture",
  "Team performance tracking",
  "Digital project management",
  "Time zone coordination",
  "Team retrospectives",
  "Time tracking software",
  "Peer reviews",
  "Retrospective meetings",
  "Project delivery",
  "Continuous improvement",
  "Agile scaling frameworks",
  "LeSS (Large Scale Scrum)",
  "Management by objectives",
  "KPIs (Key Performance Indicators)",
  "Task sequencing",
  "Kanban boards for task tracking",
  "Documentation tools",
  "Virtual sprints",
  "Cloud-based project management",
  "Time-zone independent workflows",
  "Hybrid project management",
  "Product lifecycle",
  "Agile sprint metrics",
  "GitOps",
  "Agile roadmap",
  "Team collaboration tools",
  "Agile release train",
  "Cross-functional delivery teams",
  "Minimum Viable Product (MVP)",
  "Risk mitigation planning",
  "Vendor relationship management",
  "Continuous feedback loops",
  "Project delivery framework",
  "Distributed team collaboration",
  "Time-boxing",
  "Behavior-driven development (BDD)",
  "DevOps pipeline",
  "Product backlog management",
  "User story mapping",
  "API first approach",
  "Pull request workflows",
  "Continuous integration (CI)",
  "Cross-team communication",
  "Kanban workflow",
  "Documentation templates",
  "Workload balancing",
  "Agile transformation",
  "Functional specification",
  "UML diagrams",
  "Agile performance metrics",
  "Backlog refinement",
  "Roadmap planning",
  "Conflict resolution",
  "Workstream ownership",
  "Multi-project management",
  "Scalability testing",
  "Agile documentation",
  "Portfolio management tools",
  "Agile transformation leadership",
  "Feature development cycles",
  "Quality standards implementation",
  "Cross-organizational projects",
  "Business case development",
  "Retrospective meetings",
  "Stakeholder mapping",
  "Product development lifecycle",
  "Integration testing",
  "Collaborative problem solving",
  "Dependency resolution",
  "Software configuration management",
  "Data Encryption",
  "Identity and Access Management (IAM)",
  "Public Key Infrastructure (PKI)",
  "Endpoint Protection",
  "Privacy Policy Compliance",
  "Data Privacy Regulations (GDPR, CCPA)",
  "Application Security",
  "API Security",
  "Digital Certificate Management",
  "Security Protocols",
  "Security Automation",
  "Authentication Protocols (OAuth, SAML)",
  "Encryption Algorithms (AES, RSA)",
  "Access Control",
  "Log Management",
  "Secure DevOps",
  "Privileged Access Management (PAM)",
  "Unit Testing",
  "Test-Driven Development (TDD)",
  "API Testing",
  "Non-Functional Testing",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Selenium",
  "Postman",
  "TestNG",
  "Automated Test Scripts",
  "Bug Tracking",
  "Test Reporting",
  "User Interface (UI) Testing",
  "Code Quality Tools",
  "Enterprise Mobility",
  "Agile Methodologies",
  "Project Portfolio Management (PPM)",
  "Change Control",
  "System Integration",
  "System Migration",
  "Collaboration Tools Management",
  "Product Lifecycle Management (PLM)",
  "DevOps for Enterprises",
  "Chatbots",
  "Python",
  "JavaScript",
  "Java",
  "C",
  "C++",
  "Ruby",
  "PHP",
  "Go",
  "Swift",
 
  "TypeScript",
  "Rust",
  "R",
  "Perl",
  "Scala",
  "Lua",
  "Dart",
  "Haskell",
  "Objective-C",
  "Elixir",
  "F#",
  "C#",
  "VHDL",
  "Ada",
  "SQL",
  "MATLAB",
  "Shell Scripting",
  "PowerShell",
  "ActionScript",
  "COBOL",
  "Fortran",
  "Hack",
  "Vala",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Ember.js",
  "Backbone.js",
  "Preact",
  "Mithril",
  "LitElement",
  "Node.js",
  "Express.js",
  "Django",
  "Ruby on Rails",
  "Spring Boot",
  "Flask",
  "Laravel",
  "ASP.NET",
  "Angular Universal",
  "FastAPI",
  "NestJS",
  "CakePHP",
  "Symfony",
  "Grails",
  "Spring MVC",
  "Koa.js",
  "Falcon",
  "Hapi.js",
  "Tornado",
  "Meteor.js",
  "Next.js",

  "Angular + Node.js",
  "Vue + Express",
  "React + Node.js",

  "Ionic",



  "NativeScript",
  "Sencha Touch",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "OpenCV",
  "SciPy",
  "XGBoost",
  "LightGBM",
  "Theano",
  "Caffe",
  "MXNet",
  "Fastai",
  "Hugging Face Transformers",
  "Unity",
  "Unreal Engine",
  "Godot",
  "Cocos2d",
  "LibGDX",
  "CryEngine",
  "GameMaker",
  "Phaser",
  "Pygame",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "Oracle",
  "Redis",
  "Cassandra",
  "Elasticsearch",
  "MariaDB",
  "DynamoDB",
  "Firebase Realtime Database",
  "Realm",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Jenkins",
  "Ansible",
  "Puppet",
  "Chef",
  "CircleCI",
  "GitLab CI/CD",
  "Travis CI",
  "Vagrant",
  "Kubernetes",
  "OpenShift",
  "CloudFormation",
  "Bootstrap",
  "Tailwind CSS",
  "Material-UI",
  "Foundation",
  "Bulma",
  "Sass",
  "Less",
  "PostCSS",
  "CSS Grid",
  "Flexbox",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Selenium",
  "JUnit",
  "TestNG",
  "Jasmine",
  "Karma",
  "Puppeteer",
  "Appium",
  "Cucumber",
  "PyTest",
  "RSpec",
  "Enzyme",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "SVN",
  "Mercurial",
  "jQuery",
  "Lodash",
  "Moment.js",
  "Axios",
  "Three.js",
  "Socket.io",
  "Redux",
  "Vuex",
  "RxJS",
  "Formik",
  "GraphQL",
  "Apollo Client",
  "Express Validator",
  "Passport.js",
  "REST API",
  "SOAP",
  "GraphQL API",
  "WebSockets",
  "OAuth",
  "JWT",
  "OpenAPI",
  "API Gateway",
  "Rate Limiting",
  "CORS",
  "API Testing",
  "API Documentation",
  "Swagger",
  "Postman",
  "gRPC",
  "Webhooks",
  "RESTful Design",
  "JSON",
  "XML",
  "HATEOAS",
  "API Rate Limiting",
  "Load Balancing",
  "OAuth2",
  "API Key Authentication",
  "JWT Authentication",
  "API Management",
  "API Security",
  "API Mocking",

  "Algorithm",
  "Sorting Algorithms",
  "Searching Algorithms",
  "Dynamic Programming",
  "Graph Algorithms",
  "Divide and Conquer",
  "Backtracking",
  "Greedy Algorithms",
  "Recursion",
  "Hashing",
  "Tree Traversal",
  "Depth-First Search (DFS)",
  "Breadth-First Search (BFS)",
  "A* Algorithm",
  "Dijkstra's Algorithm",
  "Kruskal's Algorithm",
  "Prim's Algorithm",
  "Bellman-Ford Algorithm",
  "Floyd-Warshall Algorithm",
  "Knapsack Problem",
  "Longest Common Subsequence",
  "Shortest Path Problem",
  "Topological Sorting",
  "Maximum Flow Problem",
  "Monte Carlo Algorithms",
  "Genetic Algorithms",
  "Simulated Annealing",
  "Neural Networks",
  "Support Vector Machines",
  "Decision Trees",
  "Random Forest",
  "K-Means Clustering",
  "Principal Component Analysis (PCA)",
  "K-Nearest Neighbors",
  "Linear Regression",
  "Logistic Regression",
  "Naive Bayes",
  "Bayesian Networks",
  "Markov Chains",
  "Hidden Markov Model",
  "Recurrent Neural Networks (RNN)",
  "Convolutional Neural Networks (CNN)",
  "Natural Language Processing (NLP)",

  "Associate Engineer",
  "Software Engineer",
  "Junior Developer",
  "Senior Developer",
  "Lead Developer",
  "Software Architect",
  "Engineering Manager",
  "Chief Technology Officer (CTO)",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Systems Engineer",
  "Network Engineer",
  "Security Engineer",
  "Embedded Systems Engineer",
  "Test Engineer",
  "Quality Assurance (QA) Engineer",
  "Project Manager",
  "Product Manager",
  "Scrum Master",
  "Agile Coach",
  "Cloud Engineer",
  "Mobile Developer",
  "Database Administrator",
  "Solutions Architect",
  "Infrastructure Engineer",
  "Site Reliability Engineer (SRE)",
  "Penetration Tester",
  "Cybersecurity Specialist",
  "Big Data Engineer",
  "BI Developer",
  "Automation Engineer",
  "Operations Engineer",

  "Bachelor's Degree in Computer Science",
  "Bachelor's Degree in Software Engineering",
  "Master's Degree in Computer Science",
  "Master's Degree in Software Engineering",
  "PhD in Computer Science",
  "PhD in Software Engineering",
  "Computer Science Bootcamp Graduate",
  "Certified ScrumMaster (CSM)",
  "Certified Kubernetes Administrator",
  "AWS Certified Solutions Architect",
  "Google Cloud Certified Professional Cloud Architect",
  "Microsoft Certified: Azure Solutions Architect Expert",
  "Certified Information Systems Security Professional (CISSP)",
  "Certified Ethical Hacker (CEH)",
  "Cisco Certified Network Associate (CCNA)",
  "CompTIA Security+",
  "Certified Data Professional (CDP)",
  "Oracle Certified Professional (OCP)",
  "MCSA: Microsoft Certified Solutions Associate",
  "Certified Python Developer",
  "Certified Java Developer",

  "Eclipse",
  "IntelliJ IDEA",
  "Visual Studio Code",
  "NetBeans",
  "PyCharm",
  "Xcode",
  "Android Studio",
  "RStudio",
  "WebStorm",
  "Sublime Text",
  "Atom",
  "Brackets",
  "JDeveloper",
  "Emacs",
  "Vim",
  "Notepad++",
  "CLion",
  "PhpStorm",
  "Rider",
  "Code::Blocks",
  "AppCode",
  "MWeb",
  "Komodo IDE",
  "Coda",
  "JetBrains Toolbox",
  "MonoDevelop",
  "Jupyter Notebooks",
  "Thonny",
  "Dev C++",
  "Spyder",
  "Arduino IDE",
  "BlueJ",
  "Scratch",
  "CodePen",
  "JSFiddle",
  "Glitch",
  "GitKraken",
  "SourceTree",
  "TortoiseSVN",
  "SmartGit",
  "Git Extensions",
  "Trello",
  "Asana",
  "Jira",
  "Monday.com",
  "Slack",
  "Microsoft Teams",
  "Notion",
  "Confluence",
  "Miro",
  "Basecamp",
  "GitHub Actions",
  "GitLab CI/CD",
  "Postman",
  "Swagger",
  "Figma",
  "Zeplin",
  "InVision",
  "Adobe XD",
  "Sketch",
  "Canva",
  "Axure RP",
  "Balsamiq",
  "Marvel App",
  "Lucidchart",
  "Visio",
  "Draw.io",
  "Trello",
  "Bamboo",
  "CircleCI",
  "XMind",
  "Miro",
  "Lucidchart",
  "Grav",
  "Notion",
  "Overleaf",
  "Rational Rose",
  "TeamCity",
  "Jenkins",
  "Azure DevOps",
]
selectedKeywords: string[] = [];
  modalOpen: boolean = false;
  currentKeyword: string = '';
  currentIndex: number = 0;

  openModal(keyword: string): void {
    this.currentKeyword = keyword;
    this.modalOpen = true;
  }

  closeModal(): void {
    this.modalOpen = false;
    this.proceedToNextKeyword();
  }

  addKeyword(): void {
    this.selectedKeywords.push(this.currentKeyword);
    console.log('Updated Selected Keywords:', this.selectedKeywords);
    this.closeModal();
    this.proceedToNextKeyword();
  }

  proceedToNextKeyword(): void {
    // Move to the next keyword after the modal closes
    this.currentIndex++;
    if (this.currentIndex < this.allKeywords.length) {
      setTimeout(() => this.openModal(this.allKeywords[this.currentIndex]), 500); // Wait for a short time before opening the next modal
    } else {
      console.log('All keywords processed:', this.selectedKeywords);
    }
  }

  startDialog(): void {
    this.selectedKeywords = [];
    this.currentIndex = 0;
    this.openModal(this.allKeywords[this.currentIndex]); // Start with the first keyword
  } */
}
